### ISSUE TITLE
  File "walkway.py", line 280, in <module>     img = cv2.imshow('Processed', processedFrame) NameError: name 'processedFrame' is not defined

### ISSUE THREAD

**Issue by maheshmd** [openalpr/cloudapi#21]
Hi friends,
I am working on the following project in github. 
https://github.com/AhmadYahya97/Fully-Automated-red-light-Violation-Detection.git

Failed to process frame
Traceback (most recent call last):
  File "walkway.py", line 280, in <module>
    img = cv2.imshow('Processed', processedFrame)
NameError: name 'processedFrame' is not defined

I tried all the possible way not resolve the error

**Comment by HarishRJ** [comment]
is this issue solved bro?
